### ISSUE TITLE
External Display not re-displaying when App is back to Foreground

### ISSUE THREAD

**Issue by nevaehph** [mybigday/react-native-external-display#142]
Hi,

I have been using the package for the past few days and it is working well. But one thing I have been noticing is that if the Application goes to the background and back to foreground, the External Display will not re display itself.

Is there a workaround for the External Display to display itself when the Application goes to the foreground?

Thank You.

**Comment by jhen0409** [comment]
I guess you're using Android. It should be an issue from [`onHostPause`](https://github.com/mybigday/react-native-external-display/blob/master/packages/react-native-external-display/android/src/main/java/com/externaldisplay/RNExternalDisplayView.java#L88). Maybe we need to handle on `onHostResume` part.
