### ISSUE TITLE
[Airplay] Only the video screen renders on external display

### ISSUE THREAD

**Issue by timkuilman** [mybigday/react-native-external-display#22]
Let me start by saying that I think this is an awesome project!

I came across the project last week so I decided to clone the repo and install a release build of the example app on my phone. I enabled Airplay on my phone and tried to stream the screens to my AppleTV. It works great with the video screen! The other screens don't seem to work. I then tried to run the app in the simulator with an external display. The other screens are rendered to the simulated external screen as expected.

**Comment by jhen0409** [comment]
You can try [the minimal implementation](https://github.com/quellish/AirPlayStoryboards) on your devices, let me know if you get different results. Otherwise it should be a problem with the device or some settings.

**Comment by timkuilman** [comment]
Thank you. I've installed that minimal implementation and it's showing me screen 0 with a button that does not do anything even though I am connected to my AppleTV. 

AppleTV model: A1625 (32gb)
tvOS: 13.3.1 (up to date)
iPhone XS (13.3.1, up to date)

I'll try to do some more investigation at a later point. If you have any suggestions please let me know.

**Comment by necixy** [comment]
Hi @timkuilman 

Thanks for pointing this out. I also came across to this package today, did you find any solution or workaround?

Thanks!

**Comment by necixy** [comment]
Hi @timkuilman 

I figured the issue, we thought that it'll connect automatically but in real device, we need to do "Screen mirroring" first and once that's connected then whenever we put this ExternalDisplay component that will be shown. 

At least that's what I observed and worked.
