### ISSUE TITLE
ScrollView is not working on external display

### ISSUE THREAD

**Issue by ionchiciuc** [mybigday/react-native-external-display#321]
I want to use a `Scrollview` on external display. 
But there is a problem, because on external display there is no `RootView` component.

I tried to change in `RNExternalDisplayView` type of `wrap` from `ReactViewGroup` to `ReactRootView`, and scroll is working.

Can it be changed?

**Comment by jhen0409** [comment]
> Can it be changed?

PR is always welcome! Thanks!

**Comment by canyzhou** [comment]
Hey, I also meet the same problem. And @ionchiciuc 's approach works for me.

I found the bug hasn't been solved for a long time. So I create the PR: https://github.com/mybigday/react-native-external-display/pull/578
