### ISSUE TITLE
TypeError: null is not an object (evaluating 'RNExternalDisplayEvent.SCREEN_INFO')

### ISSUE THREAD

**Issue by ynzier** [mybigday/react-native-external-display#463]
any way to fix this error ?
I tried to use on React Native Typescript Expo.
when I called any method from "react-native-external-display" it's always pop this error "TypeError: null is not an object (evaluating 'RNExternalDisplayEvent.SCREEN_INFO')" and crash

**Comment by jhen0409** [comment]
It looks like just a linking issue. Make sure that the `RNExternalDisplayEvent` native module is properly installed. ([installation](https://github.com/mybigday/react-native-external-display/tree/master/packages/react-native-external-display#installation))
