### ISSUE TITLE
Missing type definitions for TypeScript

### ISSUE THREAD

**Issue by david-gettins** [mybigday/react-native-external-display#515]
Please can you provide type definitions for this library? I can not seem to find any under the `@types` repo either.

<img width="713" alt="Screenshot 2022-07-08 at 11 19 42" src="https://user-images.githubusercontent.com/60265851/177973747-ad94b01a-d0b1-4a09-b090-46da4b34876e.png">

**Comment by hellostu** [comment]
Added a PR for this [here](https://github.com/mybigday/react-native-external-display/pull/776)
