### ISSUE TITLE
Android 11 - Cannot touch main screen when second display is rendered

### ISSUE THREAD

**Issue by husseinm** [mybigday/react-native-external-display#542]
On Android 11 (RK3568 Board) when the second display is rendered using `<ExternalDisplay>` the main screen loses touchscreen responsiveness (stops responding to touches) but the main and secondary screens do continue to render properly (tested w/ a clock example).

No errors are thrown in LogCat.

Simply commenting out the `<ExternalDisplay>` component immediately restores touch responsiveness (`useExternalDisplay()` hook works correctly and causes no issue, only the rendering of `<ExternalDisplay>` breaks touch responsiveness).

The exact same codebase and hardware were working on Android 8. 

Full Disclosure, this same hardware was affected by ticket #211 - perhaps the Chinese boards' modified firmware could be the issue? Not sure how to correct it since no error is appearing in LogCat and no crash/panic is occurring to know where to look.

Any ideas on this bug?

Thank you.

**Comment by husseinm** [comment]
The issue was simply the USB bus for touch being switched on the motherboard - a hardware issue not software.

**Comment by tiendat0811** [comment]
I am having the same problem. can you guide me how to bus usb to fix this problem? Thanks so much @husseinm

**Comment by demobo-com** [comment]
```
<ExternalDisplay
          mainScreenStyle={{ flex: 1 }}
          fallbackInMainScreen={false}
          screen={Object.keys(screens)[0]}
          zIndex={-1}
        >
```
Set the ExternalDisplay's zIndex to -1 will fix the problem
