### ISSUE TITLE
[Maintenance / New Architecture] - Support questions

### ISSUE THREAD

**Issue by coolersham** [mybigday/react-native-external-display#666]
Hey there, I would have two questions and I hope the owner of this repo or someone from the community can provide answers.

1. Does anyone know, whether this repo is still maintained by someone?
1. Will this package support the new architecture of react-native soon?

Thank you in advance for your answers! :)

**Comment by jhen0409** [comment]
> 1. Does anyone know, whether this repo is still maintained by someone?

We're still using it in our projects, so yes!

> 2. Will this package support the new architecture of react-native soon?

We're planning migrate to new architecture for our project, and the prerequisite is to update this lib. I plan to do it next month. Also, any contributions are welcome!
